//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalyzerTests {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnalyzerTests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las líneas no pueden superar los 130 caracteres..
        /// </summary>
        internal static string GP001Description {
            get {
                return ResourceManager.GetString("GP001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 130.
        /// </summary>
        internal static string GP001MaxCharInLine {
            get {
                return ResourceManager.GetString("GP001MaxCharInLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La línea supera los 130 caracteres, debe continuar en una nueva línea..
        /// </summary>
        internal static string GP001MessageFormat {
            get {
                return ResourceManager.GetString("GP001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caracteres por línea superados..
        /// </summary>
        internal static string GP001Title {
            get {
                return ResourceManager.GetString("GP001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Método tiene demasiadas líneas de código..
        /// </summary>
        internal static string GP002Descripcion {
            get {
                return ResourceManager.GetString("GP002Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El método contiene demasiadas líneas de código. Refactorice para mantener un código más legible..
        /// </summary>
        internal static string GP002Mensaje {
            get {
                return ResourceManager.GetString("GP002Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Metodo sobrecargado con código.
        /// </summary>
        internal static string GP002Titulo {
            get {
                return ResourceManager.GetString("GP002Titulo", resourceCulture);
            }
        }
    }
}
