//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analyzer1 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Analyzer1.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las líneas no pueden superar los 185 caracteres..
        /// </summary>
        internal static string GP001Description {
            get {
                return ResourceManager.GetString("GP001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La línea supera los 185 caracteres, debe continuar en una nueva línea..
        /// </summary>
        internal static string GP001MessageFormat {
            get {
                return ResourceManager.GetString("GP001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caracteres por línea superados..
        /// </summary>
        internal static string GP001Title {
            get {
                return ResourceManager.GetString("GP001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El método tiene demasiadas líneas de código..
        /// </summary>
        internal static string GP002Descripcion {
            get {
                return ResourceManager.GetString("GP002Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El método contiene más de 60 líneas de código. .
        /// </summary>
        internal static string GP002Mensaje {
            get {
                return ResourceManager.GetString("GP002Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El método supera la cantidad de lineas..
        /// </summary>
        internal static string GP002Titulo {
            get {
                return ResourceManager.GetString("GP002Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El comentario inicia con minúscula, cambielo a mayúscula..
        /// </summary>
        internal static string GP003Descripcion {
            get {
                return ResourceManager.GetString("GP003Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los comentarios deben iniciar en mayúscula..
        /// </summary>
        internal static string GP003Mensaje {
            get {
                return ResourceManager.GetString("GP003Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El comentario inicia con minúscula..
        /// </summary>
        internal static string GP003Titulo {
            get {
                return ResourceManager.GetString("GP003Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe haber al menos una línea en blanco entre las definiciones de métodos y las definiciones de propiedades.
        /// </summary>
        internal static string GP004Descripcion {
            get {
                return ResourceManager.GetString("GP004Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inserte una línea en blanco entre las definiciones de métodos y las definiciones de propiedades.
        /// </summary>
        internal static string GP004Mensaje {
            get {
                return ResourceManager.GetString("GP004Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta linea en blanco.
        /// </summary>
        internal static string GP004Titulo {
            get {
                return ResourceManager.GetString("GP004Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los comentarios no deben estar mezclados..
        /// </summary>
        internal static string GP005Descripcion {
            get {
                return ResourceManager.GetString("GP005Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El comentario debe posicionarse en una linea de forma independiente..
        /// </summary>
        internal static string GP005Mensaje {
            get {
                return ResourceManager.GetString("GP005Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios mezclados con codigo..
        /// </summary>
        internal static string GP005Titulo {
            get {
                return ResourceManager.GetString("GP005Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los comentarios deben terminan con punto..
        /// </summary>
        internal static string GP006Descripcion {
            get {
                return ResourceManager.GetString("GP006Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar punto final al comentario..
        /// </summary>
        internal static string GP006Mensaje {
            get {
                return ResourceManager.GetString("GP006Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El comentario deben de terminar con punto final..
        /// </summary>
        internal static string GP006Titulo {
            get {
                return ResourceManager.GetString("GP006Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo estatico debe contener el prefijo s_.
        /// </summary>
        internal static string GP007Descripcion {
            get {
                return ResourceManager.GetString("GP007Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregue el prefijo s_.
        /// </summary>
        internal static string GP007Mensaje {
            get {
                return ResourceManager.GetString("GP007Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta el prefijo s_.
        /// </summary>
        internal static string GP007Titulo {
            get {
                return ResourceManager.GetString("GP007Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo estatico debe contener el prefijo t_.
        /// </summary>
        internal static string GP008Descripcion {
            get {
                return ResourceManager.GetString("GP008Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregue el prefijo t_.
        /// </summary>
        internal static string GP008Mensaje {
            get {
                return ResourceManager.GetString("GP008Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta el prefijo t_.
        /// </summary>
        internal static string GP008Titulo {
            get {
                return ResourceManager.GetString("GP008Titulo", resourceCulture);
            }
        }
    }
}
